In [7]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_excel("./ONLINE ENGAGEMENT TASK 1.xlsx")

In [4]:
df.head()

,writing,Unnamed: 1,word game,Unnamed: 3,Unnamed: 4,Quiz,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Culinary,Unnamed: 32,Comedy,Unnamed: 34,Choreo,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,English Slam Poetry,Hindi Slam Poetry,Scrabble,Cryptic Crossie,Sacred Word Games,General Quiz,SciBizTech,MELA,Sports,India,...,Stage Play,Monoacting,Mime,cook off,tag team,Stand-Up Comedy,Improv,Group Dance,Street Battle,Just Duet
2,Atharva Bhatnagar,Piyush Pancholi,Parichay Gupta,Parichay Gupta,Parichay Gupta,Aayush Gahan,Rishvic Pushpakaran,Akshitha Yedla,Aayush Gahan,Aayush Gahan,...,Areeba faisal,Vedansh Kapoor,Ayush Kumar,Gagarin Rout,Akshat Rampuria,Keshav Anand,Keshav Anand,Dhiren Tripuramallu,Chandra Sathvik,Dhiren Tripuramallu
3,Abhilasha,Jainam Khatri,Pothula Meghana Raaj,Anup Preeyam,Neha Kolukonda,Vedanta Mohapatra,Hrushikesh Joshi,Aditya Balakrishnan,Prathamesh Patil,Prathamesh Patil,...,Simi hazarika,Dhananjay Singh Nandanwan,Manish Sahu,Ojasvv Gupta,Ojasvv Gupta,Harsh,Aaditya,Chandra Sathvik,Sashank Cheekala,Sashank Cheekala
4,Nishtha Taktewale,Nikita Srivastava,Anshul Buxy,Gnan Vikas,Malla Likhitha,Aditya Balakrishnan,Vedanta Mohapatra,Hrushikesh Joshi,Vedanta Mohapatra,Vedanta Mohapatra,...,Sreeja,Ojasvv Gupta,Krishna Chandra Paroha,Jainam Khatri,Jainam Khatri,Vrutant Chaudhari,Aditi,Sashank Cheekala,Likhita Gayathri,Chandra Sathvik

In [76]:
current_series = pd.Series(['t'])
db = pd.DataFrame()
titles = [0]
for i in df:
    if i.split()[0] != "Unnamed:":
        titles.append(i)
        current_series.reset_index(drop=True)
        db = pd.concat([db,current_series],axis =1)
        #print(current_series)
        current_series = pd.Series()
        current_series = pd.concat([current_series,df[i]],axis = 0)
        current_series = current_series.reset_index(drop=True)        
    if i.split()[0] == "Unnamed:":
        current_series = pd.concat([current_series,df[i]],axis = 0)
        current_series = current_series.reset_index(drop=True)
        
db = pd.concat([db,current_series],axis =1)

/var/folders/jw/644649297gd0_6hzy4hf6yl00000gn/T/ipykernel_17284/851518082.py:10: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  current_series = pd.Series()

In [77]:
db.columns = titles
db = db.drop([0],axis =1)
db = db.drop([0],axis =0)

In [80]:
db

,writing,word game,Quiz,Oratory,Music,Fashion,Media,FAD,Drama,Culinary,Comedy,Choreo
1,English Slam Poetry,Scrabble,General Quiz,STEW,Band Competition,Fashion Show,51 Hrs Filmmaking,Live Sketching,Street Play,cook off,Stand-Up Comedy,Group Dance
2,Atharva Bhatnagar,Parichay Gupta,Aayush Gahan,Eti Dandekar,Shweta Chauhan,Amulya Bhagyasree,Ayush Pratap Singh,Lakshit Hazarika Rabha,Parth Maheshwari,Gagarin Rout,Keshav Anand,Dhiren Tripuramallu
3,Abhilasha,Pothula Meghana Raaj,Vedanta Mohapatra,Rishit Agarwal,Jashraj,Charan Pullasi,Veeravaneni Satya Sharanya,Rupak Halder,Rishi Patel,Ojasvv Gupta,Harsh,Chandra Sathvik
4,Nishtha Taktewale,Anshul Buxy,Aditya Balakrishnan,Prarabdh Shukla,Ansh Azad,R Siva Sanjay,Deepanshu Choudhary,Rohit Kumar,Sachin Yadav,Jainam Khatri,Vrutant Chaudhari,Sashank Cheekala
5,Shalvika Alice,Prasad Kukade,Hrushikesh Joshi,Akshat Rampuria,Piyush Paikra,Vishnu Teja Vallala,Harsh Bajak,Vikramaditya,Deep Dave,Simi hazarika,Mukund Sharma,Likhita Gayathri
...,...,...,...,...,...,...,...,...,...,...,...,...
745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN